# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('grinder_setting', models.IntegerField()),
                ('temperature', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrewingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('roast_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='descriptors',
            field=models.ManyToManyField(to='coffee.Descriptor'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='roaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Roaster'),
        ),
        migrations.AddField(
            model_name='brew',
            name='coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Coffee'),
        ),
        migrations.AddField(
            model_name='brew',
            name='found_descriptors',
            field=models.ManyToManyField(to='coffee.Descriptor'),
        ),
        migrations.AddField(
            model_name='brew',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.BrewingMethod'),
        ),
    ]
