# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brew',
            name='coffee',
        ),
        migrations.AddField(
            model_name='brew',
            name='coffee_bag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coffee.CoffeeBag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brew',
            name='rating',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='roaster_comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='descriptors',
            field=models.ManyToManyField(blank=True, to='coffee.Descriptor'),
        ),
    ]
