# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20170401_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='brew',
            name='coffee_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brew',
            name='water_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brew',
            name='found_descriptors',
            field=models.ManyToManyField(blank=True, to='coffee.Descriptor'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='roast_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.RoastProfile'),
        ),
    ]
