# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_auto_20170402_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='bloom',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Bloom'), (2, 'No bloom')], default=0),
        ),
        migrations.AddField(
            model_name='brew',
            name='brew_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
