# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20170402_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
