# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20170601_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewingmethod',
            name='default_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.Filter'),
        ),
    ]
