# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_brewingmethod_default_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pouring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('wait_time', models.IntegerField(blank=True, null=True)),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Brew')),
            ],
        ),
    ]
