# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_auto_20170625_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagpicture',
            name='image',
            field=models.ImageField(default='', upload_to='bags/full/'),
            preserve_default=False,
        ),
    ]
