# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_bagpicture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='processing',
            field=models.IntegerField(blank=True, choices=[(1, 'Washed'), (2, 'Dry'), (3, 'Honey')], null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='short_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
