# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0015_auto_20170724_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagpicture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='bags/thumbs/'),
        ),
    ]
