# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0016_bagpicture_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='result_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffeebag',
            name='roaster_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffeebag',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not finished'), (1, 'Finished'), (2, 'Thrown away'), (3, 'Given away')], default=0),
        ),
        migrations.AlterField(
            model_name='bagpicture',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_pictures', to='coffee.CoffeeBag'),
        ),
    ]
