# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-01 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0018_auto_20171001_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('comment', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='brew',
            name='grinder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coffee.Grinder'),
        ),
    ]
