# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-16 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0019_auto_20171001_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='grinder',
            name='adjust_type',
            field=models.IntegerField(choices=[(0, 'Simple'), (1, 'Aergrind')], default=0),
        ),
    ]
