# Generated by Django 2.0.7 on 2018-12-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0020_grinder_adjust_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='brew',
            name='extraction',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Недоэксракт'), (0, 'Баланс'), (1, 'Лёгкий переэкстракт'), (2, 'Переэкстракт')], null=True),
        ),
    ]
